@echo off
chcp 65001 >nul 2>&1
title ComfyPack - Installer
setlocal enabledelayedexpansion

echo.
echo ====================================================
echo    ComfyPack Installer
echo    ComfyUI + Hooking Server Docker Deployment
echo ====================================================
echo.

:: ─── Docker Check ───────────────────────────────────────
where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker is not installed.
    echo.
    echo Please install Docker Desktop first:
    echo https://www.docker.com/products/docker-desktop/
    echo.
    echo After installation, start Docker Desktop and run this script again.
    pause
    exit /b 1
)

docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker is not running.
    echo Please start Docker Desktop and try again.
    pause
    exit /b 1
)

echo [OK] Docker is running.
echo.

:: ─── Project Path ───────────────────────────────────────
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."
cd /d "%PROJECT_DIR%"
set "PROJECT_DIR=%cd%"

echo Project path: %PROJECT_DIR%
echo.

:: ─── Config ─────────────────────────────────────────────
set "ENV_FILE=%PROJECT_DIR%\.env"
set "CONFIG_DIR=%PROJECT_DIR%\config"

if not exist "%ENV_FILE%" (
    echo.
    echo --- Initial Setup ---
    echo.

    set "MODEL_INPUT="
    set /p "MODEL_INPUT=Enter model folder path (default: %PROJECT_DIR%\models): "
    if "!MODEL_INPUT!"=="" set "MODEL_INPUT=%PROJECT_DIR%\models"

    set "PATCH_INPUT="
    set /p "PATCH_INPUT=Enter patch data folder path (default: %PROJECT_DIR%\patch_data): "
    if "!PATCH_INPUT!"=="" set "PATCH_INPUT=%PROJECT_DIR%\patch_data"

    set "CONFIG_INPUT="
    set /p "CONFIG_INPUT=Enter config.json path (default: %PROJECT_DIR%\config\config.json): "
    if "!CONFIG_INPUT!"=="" set "CONFIG_INPUT=%PROJECT_DIR%\config\config.json"

    set "MODEL_PATH_DOCKER=!MODEL_INPUT:\=/!"
    set "PATCH_PATH_DOCKER=!PATCH_INPUT:\=/!"
    set "CONFIG_PATH_DOCKER=!CONFIG_INPUT:\=/!"

    echo # ComfyPack Configuration > "%ENV_FILE%"
    echo # Generated by install_en.bat >> "%ENV_FILE%"
    echo MODEL_PATH=!MODEL_PATH_DOCKER! >> "%ENV_FILE%"
    echo PATCH_DATA_PATH=!PATCH_PATH_DOCKER! >> "%ENV_FILE%"
    echo CONFIG_PATH=!CONFIG_PATH_DOCKER! >> "%ENV_FILE%"
    echo COMFYUI_PORT=8188 >> "%ENV_FILE%"
    echo HOOKING_PORT=8189 >> "%ENV_FILE%"

    echo.
    echo [OK] .env file created: %ENV_FILE%

    if not exist "!MODEL_INPUT!" mkdir "!MODEL_INPUT!"
    if not exist "!PATCH_INPUT!" (
        mkdir "!PATCH_INPUT!"
        mkdir "!PATCH_INPUT!\asset"
        mkdir "!PATCH_INPUT!\asset_data"
        mkdir "!PATCH_INPUT!\chain_presets"
        mkdir "!PATCH_INPUT!\customprompt"
        mkdir "!PATCH_INPUT!\pose_data"
        mkdir "!PATCH_INPUT!\auto_complete"
        mkdir "!PATCH_INPUT!\workflow"
        mkdir "!PATCH_INPUT!\mode_workflow"
        echo [OK] Patch data folders created: !PATCH_INPUT!
    )
    if not exist "!CONFIG_INPUT!\.." mkdir "!CONFIG_INPUT!\.."
    if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
) else (
    echo [OK] Using existing .env file: %ENV_FILE%
)

:: ─── Main Menu ──────────────────────────────────────────
:menu
echo.
echo ====================================================
echo    ComfyPack Menu
echo ====================================================
echo.
echo   1. Build Docker images (local)
echo   2. Pull images from Docker Hub (recommended)
echo   3. Start ComfyPack
echo   4. Stop ComfyPack
echo   5. Check status
echo   6. Reset settings (reconfigure .env)
echo   0. Exit
echo.
set "CHOICE="
set /p "CHOICE=Select [0-6]: "

if "%CHOICE%"=="1" goto build
if "%CHOICE%"=="2" goto pull
if "%CHOICE%"=="3" goto start
if "%CHOICE%"=="4" goto stop
if "%CHOICE%"=="5" goto status
if "%CHOICE%"=="6" goto reset
if "%CHOICE%"=="0" exit /b 0
goto menu

:build
echo.
echo Building Docker images. This may take 30-60 minutes...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" build --no-cache
if %errorlevel%==0 (
    echo.
    echo [OK] Image build complete!
    echo.
    echo Cleaning up unused old images...
    docker image prune -f
) else (
    echo.
    echo [X] Image build failed. Check the error messages above.
)
pause
goto menu

:pull
echo.
echo Pulling images from Docker Hub...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" pull
if %errorlevel%==0 (
    echo.
    echo [OK] Image download complete!
    echo.
    echo Cleaning up unused old images...
    docker image prune -f
) else (
    echo.
    echo [X] Image download failed.
    echo     Images may not be on Docker Hub yet.
    echo     Try option 1 (local build) instead.
)
pause
goto menu

:start
echo.
echo Starting ComfyPack...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" up -d
if %errorlevel%==0 (
    echo.
    echo ====================================================
    echo    ComfyPack is running!
    echo ====================================================
    echo.
    echo    ComfyUI:        http://localhost:8188
    echo    Hooking Server:  http://localhost:8189
    echo.
    echo    First run may take time to load models.
    echo    To stop, run this script and select option 4.
    echo.
) else (
    echo.
    echo [X] Failed to start. Check the error messages above.
)
pause
goto menu

:stop
echo.
echo Stopping ComfyPack...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" down
echo [OK] ComfyPack stopped.
pause
goto menu

:status
echo.
echo ComfyPack status:
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" ps
echo.
pause
goto menu

:reset
echo.
del "%ENV_FILE%" 2>nul
echo [OK] .env file deleted. You will be prompted again on next run.
pause
goto menu
