@echo off
chcp 65001 >nul 2>&1
title ComfyPack - 설치 프로그램
setlocal enabledelayedexpansion

echo.
echo ══════════════════════════════════════════════════════
echo    ComfyPack 설치 프로그램
echo    ComfyUI + Hooking Server Docker 배포
echo ══════════════════════════════════════════════════════
echo.
echo    신규 설치: 2 =^> 3
echo    업데이트:  6
echo.
echo    나머지 메뉴:
echo      1 - 직접 이미지 빌드 (느림, 인터넷 안 될 때)
echo      4 - ComfyPack(컨테이너) 중지
echo      5 - 실행 상태 확인
echo      7 - 설정 초기화 (.env 삭제 후 재생성)
echo.
echo ══════════════════════════════════════════════════════
echo.

:: ─── Docker 확인 ────────────────────────────────────────
where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker가 설치되어 있지 않습니다.
    echo.
    echo Docker Desktop을 먼저 설치해주세요:
    echo https://www.docker.com/products/docker-desktop/
    echo.
    echo 설치 후 Docker Desktop을 실행하고 이 스크립트를 다시 실행하세요.
    pause
    exit /b 1
)

docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker가 실행 중이 아닙니다.
    echo Docker Desktop을 실행한 후 다시 시도하세요.
    pause
    exit /b 1
)

echo [OK] Docker가 정상적으로 실행 중입니다.
echo.

:: ─── 스크립트 위치 기준으로 프로젝트 경로 설정 ─────────
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."
cd /d "%PROJECT_DIR%"
set "PROJECT_DIR=%cd%"

echo 프로젝트 경로: %PROJECT_DIR%
echo.

:: ─── 설정 파일 확인/생성 ────────────────────────────────
set "ENV_FILE=%PROJECT_DIR%\.env"
set "CONFIG_DIR=%PROJECT_DIR%\config"

:: 고정 경로 (패키지 내부)
set "MODEL_DIR=%PROJECT_DIR%\models"
set "PATCH_DIR=%PROJECT_DIR%\patch_data"
set "CONFIG_FILE=%CONFIG_DIR%\config.json"

:: 경로의 백슬래시를 슬래시로 변환 (Docker Compose용)
set "MODEL_PATH_DOCKER=!MODEL_DIR:\=/!"
set "PATCH_PATH_DOCKER=!PATCH_DIR:\=/!"
set "CONFIG_PATH_DOCKER=!CONFIG_FILE:\=/!"

if not exist "%ENV_FILE%" (
    echo.
    echo ─── 초기 설정 ──────────────────────────────────────
    echo.
    goto create_env
) else (
    echo [OK] 기존 .env 파일을 사용합니다: %ENV_FILE%
    goto skip_env
)

:create_env
echo # ComfyPack Configuration> "%ENV_FILE%"
echo # Generated by install.bat>> "%ENV_FILE%"
echo MODEL_PATH=!MODEL_PATH_DOCKER!>> "%ENV_FILE%"
echo PATCH_DATA_PATH=!PATCH_PATH_DOCKER!>> "%ENV_FILE%"
echo CONFIG_PATH=!CONFIG_PATH_DOCKER!>> "%ENV_FILE%"
echo COMFYUI_PORT=8188>> "%ENV_FILE%"
echo HOOKING_PORT=8189>> "%ENV_FILE%"
echo [OK] .env 파일이 생성되었습니다: %ENV_FILE%

if not exist "%MODEL_DIR%" mkdir "%MODEL_DIR%"
if not exist "%PATCH_DIR%" (
    mkdir "%PATCH_DIR%"
    mkdir "%PATCH_DIR%\asset"
    mkdir "%PATCH_DIR%\asset_data"
    mkdir "%PATCH_DIR%\chain_presets"
    mkdir "%PATCH_DIR%\customprompt"
    mkdir "%PATCH_DIR%\pose_data"
    mkdir "%PATCH_DIR%\auto_complete"
    mkdir "%PATCH_DIR%\workflow"
    mkdir "%PATCH_DIR%\mode_workflow"
    echo [OK] 패치 데이터 폴더가 생성되었습니다.
)
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
if not exist "%CONFIG_FILE%" (
    echo {} > "%CONFIG_FILE%"
    echo [OK] 빈 config.json 파일을 생성했습니다.
)
echo [OK] 초기 설정이 완료되었습니다.

:skip_env

:: ─── WSL2 메모리 설정 ─────────────────────────────────────
set "WSLCONFIG_SRC=%PROJECT_DIR%\config\wslconfig"
set "WSLCONFIG_DST=%USERPROFILE%\.wslconfig"
if exist "%WSLCONFIG_SRC%" (
    if not exist "%WSLCONFIG_DST%" (
        copy /y "%WSLCONFIG_SRC%" "%WSLCONFIG_DST%" >nul
        echo [OK] WSL2 메모리 설정 적용 (16GB). Docker 재시작 시 반영됩니다.
    ) else (
        fc "%WSLCONFIG_SRC%" "%WSLCONFIG_DST%" >nul 2>&1
        if !errorlevel! neq 0 (
            copy /y "%WSLCONFIG_SRC%" "%WSLCONFIG_DST%" >nul
            echo [OK] WSL2 메모리 설정이 업데이트되었습니다. Docker 재시작 시 반영됩니다.
        )
    )
)

:: ─── 메인 메뉴 ──────────────────────────────────────────
:menu
echo.
echo ══════════════════════════════════════════════════════
echo    ComfyPack 메뉴
echo ══════════════════════════════════════════════════════
echo.
echo   1. Docker 이미지 빌드 (로컬)
echo   2. Docker Hub에서 이미지 다운로드 (권장)
echo   3. ComfyPack(컨테이너) 시작
echo   4. ComfyPack(컨테이너) 중지
echo   5. 실행 상태
echo   6. 업데이트 (최신 버전으로)
echo   7. 설정 초기화 (.env 재설정)
echo   8. 컨테이너 삭제
echo   9. 이미지 삭제 (디스크 공간 확보)
echo   0. 종료
echo.
set "CHOICE="
set /p "CHOICE=선택하세요 [0-9]: "

if "%CHOICE%"=="1" goto build
if "%CHOICE%"=="2" goto pull
if "%CHOICE%"=="3" goto start
if "%CHOICE%"=="4" goto stop
if "%CHOICE%"=="5" goto status
if "%CHOICE%"=="6" goto update
if "%CHOICE%"=="7" goto reset
if "%CHOICE%"=="8" goto remove_containers
if "%CHOICE%"=="9" goto remove_images
if "%CHOICE%"=="0" exit /b 0
goto menu

:: ─── 빌드 ───────────────────────────────────────────────
:build
echo.
echo Docker 이미지를 빌드합니다. 시간이 오래 걸릴 수 있습니다 (30분~1시간)...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" build --no-cache
if %errorlevel%==0 (
    echo.
    echo [OK] 이미지 빌드가 완료되었습니다!
    echo.
    echo 사용하지 않는 이전 이미지를 정리합니다...
    docker image prune -f
) else (
    echo.
    echo [X] 이미지 빌드에 실패했습니다. 오류 메시지를 확인하세요.
)
pause
goto menu

:: ─── Pull ───────────────────────────────────────────────
:pull
echo.
echo Docker Hub에서 이미지를 다운로드합니다...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" pull
if %errorlevel%==0 (
    echo.
    echo [OK] 이미지 다운로드가 완료되었습니다!
    echo.
    echo 사용하지 않는 이전 이미지를 정리합니다...
    docker image prune -f
) else (
    echo.
    echo [X] 이미지 다운로드에 실패했습니다.
    echo     Docker Hub에 이미지가 아직 업로드되지 않았을 수 있습니다.
    echo     옵션 1(로컬 빌드)을 시도해보세요.
)
pause
goto menu

:: ─── 시작 ───────────────────────────────────────────────
:start
echo.
echo ComfyPack(컨테이너)을 시작합니다...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" up -d
if %errorlevel%==0 (
    echo.
    echo ══════════════════════════════════════════════════════
    echo    ComfyPack(컨테이너)이 시작되었습니다!
    echo ══════════════════════════════════════════════════════
    echo.
    echo    ComfyUI:       http://localhost:8188
    echo    Hooking Server: http://localhost:8189
    echo.
    echo    처음 실행 시 모델 로딩에 시간이 걸릴 수 있습니다.
    echo    중지하려면 이 스크립트를 다시 실행하고 옵션 4를 선택하세요.
    echo.
) else (
    echo.
    echo [X] 시작에 실패했습니다. 오류 메시지를 확인하세요.
)
pause
goto menu

:: ─── 중지 ───────────────────────────────────────────────
:stop
echo.
echo ComfyPack(컨테이너)을 중지합니다...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" down
echo [OK] ComfyPack(컨테이너)이 중지되었습니다.
pause
goto menu

:: ─── 상태 확인 ──────────────────────────────────────────
:status
echo.
echo ComfyPack(컨테이너) 상태:
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" ps
echo.
pause
goto menu

:: ─── 설정 초기화 ────────────────────────────────────────
:reset
echo.
echo [!] .env 파일을 삭제하시겠습니까?
echo     다음 실행 시 기본값으로 다시 생성됩니다.
echo.
set "CONFIRM_RESET="
set /p "CONFIRM_RESET=삭제하시겠습니까? (y/N): "
if /i not "%CONFIRM_RESET%"=="y" goto menu
del "%ENV_FILE%" 2>nul
echo [OK] .env 파일이 삭제되었습니다. 다음 실행 시 다시 설정합니다.
pause
goto menu

:: ─── 업데이트 ──────────────────────────────────────────
:update
echo.
echo ══════════════════════════════════════════════════════
echo    ComfyPack(컨테이너) 업데이트
echo ══════════════════════════════════════════════════════
echo.

echo [1/4] 최신 코드를 다운로드합니다...
git -C "%PROJECT_DIR%" pull
if %errorlevel% neq 0 (
    echo.
    echo [X] 코드 업데이트에 실패했습니다.
    echo     Git이 설치되어 있지 않거나, Git 저장소가 아닐 수 있습니다.
    echo     수동으로 다운로드하여 덮어씌워주세요.
    pause
    goto menu
)

echo.
echo [2/4] 최신 Docker 이미지를 다운로드합니다...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" pull

echo.
echo [3/4] 이전 이미지를 정리합니다...
docker image prune -f

echo.
echo [4/4] ComfyPack(컨테이너)을 재시작합니다...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" up -d

echo.
echo [OK] 업데이트가 완료되었습니다!
pause
goto menu

:: ─── 컨테이너 삭제 ──────────────────────────────────────
:remove_containers
echo.
echo ComfyPack(컨테이너)을 삭제합니다...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" down
echo [OK] 컨테이너가 삭제되었습니다. 다시 시작하려면 메뉴 3을 선택하세요.
pause
goto menu

:: ─── 이미지 삭제 ────────────────────────────────────────
:remove_images
echo.
echo [!] ComfyPack Docker 이미지를 삭제합니다.
echo     모델, 패치 데이터, 설정은 유지됩니다. 이미지만 삭제됩니다.
echo.
set "CONFIRM="
set /p "CONFIRM=정말 삭제하시겠습니까? (y/N): "
if /i not "%CONFIRM%"=="y" goto menu

docker compose -f "%PROJECT_DIR%\docker-compose.yml" down --rmi all
if %errorlevel%==0 (
    echo.
    echo [OK] 이미지가 삭제되었습니다. 디스크 공간이 확보되었습니다.
    echo     다시 사용하려면 메뉴 1 또는 2로 이미지를 받으세요.
    echo.
    echo 사용하지 않는 이미지를 추가 정리합니다...
    docker image prune -f
) else (
    echo.
    echo [X] 이미지 삭제에 실패했습니다.
)
pause
goto menu

:: ─── 예기치 않은 종료 방지 ────────────────────────────────
echo.
echo [!] 스크립트가 예상치 못하게 종료되었습니다. 위 오류를 확인하세요.
pause
exit /b 1
