@echo off
:: Prevent window from closing on error
if "%~1"=="_RUN_" goto main
start "ComfyPack" cmd /k "%~f0" _RUN_
goto :EOF

:main
chcp 65001 >nul 2>&1
title ComfyPack - Installer
setlocal enabledelayedexpansion

echo.
echo ====================================================
echo    ComfyPack Installer
echo    ComfyUI + Hooking Server Docker Deployment
echo ====================================================
echo.
echo    New install: 2 =^> 3
echo    Update:      6
echo.
echo    Other menus:
echo      1 - Build images locally (slow, use when offline)
echo      4 - Stop ComfyPack (containers)
echo      5 - Check running status
echo      7 - Reset settings (delete .env and regenerate)
echo.
echo ====================================================
echo.

:: ─── Docker Check ───────────────────────────────────────
where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker is not installed.
    echo.
    echo Please install Docker Desktop first:
    echo https://www.docker.com/products/docker-desktop/
    echo.
    echo After installation, start Docker Desktop and run this script again.
    pause
    exit
)

docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker is not running.
    echo Please start Docker Desktop and try again.
    pause
    exit
)

echo [OK] Docker is running.
echo.

:: ─── Project Path ───────────────────────────────────────
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."
cd /d "%PROJECT_DIR%"
set "PROJECT_DIR=%cd%"

echo Project path: %PROJECT_DIR%
echo.

:: ─── Config ─────────────────────────────────────────────
set "ENV_FILE=%PROJECT_DIR%\.env"
set "CONFIG_DIR=%PROJECT_DIR%\config"

:: Fixed paths (inside package)
set "MODEL_DIR=%PROJECT_DIR%\models"
set "PATCH_DIR=%PROJECT_DIR%\patch_data"
set "CONFIG_FILE=%CONFIG_DIR%\config.json"

:: Convert backslashes to forward slashes (for Docker Compose)
set "MODEL_PATH_DOCKER=!MODEL_DIR:\=/!"
set "PATCH_PATH_DOCKER=!PATCH_DIR:\=/!"
set "CONFIG_PATH_DOCKER=!CONFIG_FILE:\=/!"

if not exist "%ENV_FILE%" (
    echo.
    echo --- Initial Setup ---
    echo.
    goto create_env
) else (
    echo [OK] Using existing .env file: %ENV_FILE%
    goto skip_env
)

:create_env
echo # ComfyPack Configuration> "%ENV_FILE%"
echo # Generated by install_en.bat>> "%ENV_FILE%"
echo MODEL_PATH=!MODEL_PATH_DOCKER!>> "%ENV_FILE%"
echo PATCH_DATA_PATH=!PATCH_PATH_DOCKER!>> "%ENV_FILE%"
echo CONFIG_PATH=!CONFIG_PATH_DOCKER!>> "%ENV_FILE%"
echo COMFYUI_PORT=8188>> "%ENV_FILE%"
echo HOOKING_PORT=8189>> "%ENV_FILE%"
echo [OK] .env file created: %ENV_FILE%

if not exist "%MODEL_DIR%" mkdir "%MODEL_DIR%"
if not exist "%PATCH_DIR%" (
    mkdir "%PATCH_DIR%"
    mkdir "%PATCH_DIR%\asset"
    mkdir "%PATCH_DIR%\asset_data"
    mkdir "%PATCH_DIR%\chain_presets"
    mkdir "%PATCH_DIR%\customprompt"
    mkdir "%PATCH_DIR%\pose_data"
    mkdir "%PATCH_DIR%\auto_complete"
    mkdir "%PATCH_DIR%\workflow"
    mkdir "%PATCH_DIR%\mode_workflow"
    echo [OK] Patch data folders created.
)
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
if not exist "%CONFIG_FILE%" (
    echo {} > "%CONFIG_FILE%"
    echo [OK] Empty config.json created.
)
echo [OK] Initial setup complete.

:skip_env

:: ─── WSL2 memory config ─────────────────────────────────
set "WSLCONFIG_SRC=%PROJECT_DIR%\config\wslconfig"
set "WSLCONFIG_DST=%USERPROFILE%\.wslconfig"
if exist "%WSLCONFIG_SRC%" (
    if not exist "%WSLCONFIG_DST%" (
        copy /y "%WSLCONFIG_SRC%" "%WSLCONFIG_DST%" >nul
        echo [OK] WSL2 memory limit applied - 16GB. Takes effect on Docker restart.
    ) else (
        fc "%WSLCONFIG_SRC%" "%WSLCONFIG_DST%" >nul 2>&1
        if !errorlevel! neq 0 (
            copy /y "%WSLCONFIG_SRC%" "%WSLCONFIG_DST%" >nul
            echo [OK] WSL2 memory config updated. Takes effect on Docker restart.
        )
    )
)

:: ─── Main Menu ──────────────────────────────────────────
:menu
echo.
echo ====================================================
echo    ComfyPack Menu
echo ====================================================
echo.
echo   1. Build Docker images (local)
echo   2. Pull images from Docker Hub (recommended)
echo   3. Start ComfyPack (containers)
echo   4. Stop ComfyPack (containers)
echo   5. Running status
echo   6. Update to latest version
echo   7. Reset settings (reconfigure .env)
echo   8. Remove containers
echo   9. Remove images (free disk space)
echo   0. Exit
echo.
set "CHOICE="
set /p "CHOICE=Select [0-9]: "

if "%CHOICE%"=="1" goto build
if "%CHOICE%"=="2" goto pull
if "%CHOICE%"=="3" goto start
if "%CHOICE%"=="4" goto stop
if "%CHOICE%"=="5" goto status
if "%CHOICE%"=="6" goto update
if "%CHOICE%"=="7" goto reset
if "%CHOICE%"=="8" goto remove_containers
if "%CHOICE%"=="9" goto remove_images
if "%CHOICE%"=="0" goto quit
goto menu

:build
echo.
echo Building Docker images. This may take 30-60 minutes...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" build --no-cache
if %errorlevel%==0 (
    echo.
    echo [OK] Image build complete!
    echo.
    echo Cleaning up unused old images...
    docker image prune -f
) else (
    echo.
    echo [X] Image build failed. Check the error messages above.
)
pause
goto menu

:pull
echo.
echo Pulling images from Docker Hub...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" pull
if %errorlevel%==0 (
    echo.
    echo [OK] Image download complete!
    echo.
    echo Cleaning up unused old images...
    docker image prune -f
) else (
    echo.
    echo [X] Image download failed.
    echo     Images may not be on Docker Hub yet.
    echo     Try option 1 (local build) instead.
)
pause
goto menu

:start
echo.
echo Starting ComfyPack (containers)...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" up -d
if %errorlevel%==0 (
    echo.
    echo ====================================================
    echo    ComfyPack (containers) is running!
    echo ====================================================
    echo.
    echo    ComfyUI:        http://localhost:8188
    echo    Hooking Server:  http://localhost:8189
    echo.
    echo    First run may take time to load models.
    echo    To stop, run this script and select option 4.
    echo.
) else (
    echo.
    echo [X] Failed to start. Check the error messages above.
)
pause
goto menu

:stop
echo.
echo Stopping ComfyPack (containers)...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" down
echo [OK] ComfyPack (containers) stopped.
pause
goto menu

:status
echo.
echo ComfyPack (containers) status:
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" ps
echo.
pause
goto menu

:reset
echo.
echo [!] Delete .env file?
echo     It will be regenerated with defaults on next run.
echo.
set "CONFIRM_RESET="
set /p "CONFIRM_RESET=Are you sure? (y/N): "
if /i not "%CONFIRM_RESET%"=="y" goto menu
del "%ENV_FILE%" 2>nul
echo [OK] .env file deleted. Run again to reconfigure.
pause
goto menu

:: ─── Update ──────────────────────────────────────────────
:update
echo.
echo ====================================================
echo    ComfyPack (containers) Update
echo ====================================================
echo.

echo [1/4] Downloading latest code...
git -C "%PROJECT_DIR%" pull
if %errorlevel% neq 0 (
    echo.
    echo [X] Code update failed.
    echo     Git may not be installed, or this is not a Git repository.
    echo     Please download manually and overwrite files.
    pause
    goto menu
)

echo.
echo [2/4] Downloading latest Docker images...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" pull

echo.
echo [3/4] Cleaning up old images...
docker image prune -f

echo.
echo [4/4] Restarting ComfyPack (containers)...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" up -d

echo.
echo [OK] Update complete!
pause
goto menu

:: ─── Remove Containers ──────────────────────────────────
:remove_containers
echo.
echo Removing ComfyPack (containers)...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" down
echo [OK] Containers removed. Select menu 3 to start again.
pause
goto menu

:: ─── Remove Images ──────────────────────────────────────
:remove_images
echo.
echo [!] This will remove ComfyPack Docker images.
echo     Models, patch data, and config will be kept. Only images are removed.
echo.
set "CONFIRM="
set /p "CONFIRM=Are you sure? (y/N): "
if /i not "%CONFIRM%"=="y" goto menu

docker compose -f "%PROJECT_DIR%\docker-compose.yml" down --rmi all
if %errorlevel%==0 (
    echo.
    echo [OK] Images removed. Disk space freed.
    echo     Use menu 1 or 2 to download images again.
    echo.
    echo Cleaning up remaining unused images...
    docker image prune -f
) else (
    echo.
    echo [X] Failed to remove images.
)
pause
goto menu

:quit
echo.
pause
exit
