@echo off
chcp 65001 >nul 2>&1
title ComfyPack - 설치 프로그램
setlocal enabledelayedexpansion

echo.
echo ══════════════════════════════════════════════════════
echo    ComfyPack 설치 프로그램
echo    ComfyUI + Hooking Server Docker 배포
echo ══════════════════════════════════════════════════════
echo.

:: ─── Docker 확인 ────────────────────────────────────────
where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker가 설치되어 있지 않습니다.
    echo.
    echo Docker Desktop을 먼저 설치해주세요:
    echo https://www.docker.com/products/docker-desktop/
    echo.
    echo 설치 후 Docker Desktop을 실행하고 이 스크립트를 다시 실행하세요.
    pause
    exit /b 1
)

docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Docker가 실행 중이 아닙니다.
    echo Docker Desktop을 실행한 후 다시 시도하세요.
    pause
    exit /b 1
)

echo [OK] Docker가 정상적으로 실행 중입니다.
echo.

:: ─── 스크립트 위치 기준으로 프로젝트 경로 설정 ─────────
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."
cd /d "%PROJECT_DIR%"
set "PROJECT_DIR=%cd%"

echo 프로젝트 경로: %PROJECT_DIR%
echo.

:: ─── 설정 파일 확인/생성 ────────────────────────────────
set "ENV_FILE=%PROJECT_DIR%\.env"
set "CONFIG_DIR=%PROJECT_DIR%\config"

if not exist "%ENV_FILE%" (
    echo.
    echo ─── 초기 설정 ──────────────────────────────────────
    echo.

    :: 모델 경로 입력
    set "MODEL_INPUT="
    set /p "MODEL_INPUT=모델 파일이 있는 폴더 경로를 입력하세요 (기본값: %PROJECT_DIR%\models): "
    if "!MODEL_INPUT!"=="" set "MODEL_INPUT=%PROJECT_DIR%\models"

    :: 패치 데이터 경로 입력
    set "PATCH_INPUT="
    set /p "PATCH_INPUT=패치 데이터 폴더 경로를 입력하세요 (기본값: %PROJECT_DIR%\patch_data): "
    if "!PATCH_INPUT!"=="" set "PATCH_INPUT=%PROJECT_DIR%\patch_data"

    :: config.json 경로
    set "CONFIG_INPUT="
    set /p "CONFIG_INPUT=config.json 경로를 입력하세요 (기본값: %PROJECT_DIR%\config\config.json): "
    if "!CONFIG_INPUT!"=="" set "CONFIG_INPUT=%PROJECT_DIR%\config\config.json"
    if not exist "!CONFIG_INPUT!" (
        if not exist "!CONFIG_INPUT!\.." mkdir "!CONFIG_INPUT!\.."
        echo {} > "!CONFIG_INPUT!"
        echo [OK] 빈 config.json 파일을 생성했습니다.
    )

    :: 경로의 백슬래시를 슬래시로 변환 (Docker Compose용)
    set "MODEL_PATH_DOCKER=!MODEL_INPUT:\=/!"
    set "PATCH_PATH_DOCKER=!PATCH_INPUT:\=/!"
    set "CONFIG_PATH_DOCKER=!CONFIG_INPUT:\=/!"

    :: .env 파일 생성
    echo # ComfyPack Configuration > "%ENV_FILE%"
    echo # Generated by install.bat >> "%ENV_FILE%"
    echo MODEL_PATH=!MODEL_PATH_DOCKER! >> "%ENV_FILE%"
    echo PATCH_DATA_PATH=!PATCH_PATH_DOCKER! >> "%ENV_FILE%"
    echo CONFIG_PATH=!CONFIG_PATH_DOCKER! >> "%ENV_FILE%"
    echo COMFYUI_PORT=8188 >> "%ENV_FILE%"
    echo HOOKING_PORT=8189 >> "%ENV_FILE%"

    echo.
    echo [OK] .env 파일이 생성되었습니다: %ENV_FILE%

    :: 필요한 폴더 생성
    if not exist "!MODEL_INPUT!" mkdir "!MODEL_INPUT!"
    if not exist "!PATCH_INPUT!" (
        mkdir "!PATCH_INPUT!"
        mkdir "!PATCH_INPUT!\asset"
        mkdir "!PATCH_INPUT!\asset_data"
        mkdir "!PATCH_INPUT!\chain_presets"
        mkdir "!PATCH_INPUT!\customprompt"
        mkdir "!PATCH_INPUT!\pose_data"
        mkdir "!PATCH_INPUT!\auto_complete"
        mkdir "!PATCH_INPUT!\workflow"
        mkdir "!PATCH_INPUT!\mode_workflow"
        echo [OK] 패치 데이터 폴더가 생성되었습니다: !PATCH_INPUT!
    )
    if not exist "!CONFIG_INPUT!\.." mkdir "!CONFIG_INPUT!\.."
    if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
) else (
    echo [OK] 기존 .env 파일을 사용합니다: %ENV_FILE%
)

:: ─── 메인 메뉴 ──────────────────────────────────────────
:menu
echo.
echo ══════════════════════════════════════════════════════
echo    ComfyPack 메뉴
echo ══════════════════════════════════════════════════════
echo.
echo   1. Docker 이미지 빌드 (로컬)
echo   2. Docker Hub에서 이미지 다운로드 (권장)
echo   3. ComfyPack 시작
echo   4. ComfyPack 중지
echo   5. 상태 확인
echo   6. 설정 초기화 (.env 재설정)
echo   0. 종료
echo.
set "CHOICE="
set /p "CHOICE=선택하세요 [0-6]: "

if "%CHOICE%"=="1" goto build
if "%CHOICE%"=="2" goto pull
if "%CHOICE%"=="3" goto start
if "%CHOICE%"=="4" goto stop
if "%CHOICE%"=="5" goto status
if "%CHOICE%"=="6" goto reset
if "%CHOICE%"=="0" exit /b 0
goto menu

:: ─── 빌드 ───────────────────────────────────────────────
:build
echo.
echo Docker 이미지를 빌드합니다. 시간이 오래 걸릴 수 있습니다 (30분~1시간)...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" build --no-cache
if %errorlevel%==0 (
    echo.
    echo [OK] 이미지 빌드가 완료되었습니다!
) else (
    echo.
    echo [X] 이미지 빌드에 실패했습니다. 오류 메시지를 확인하세요.
)
pause
goto menu

:: ─── Pull ───────────────────────────────────────────────
:pull
echo.
echo Docker Hub에서 이미지를 다운로드합니다...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" pull
if %errorlevel%==0 (
    echo.
    echo [OK] 이미지 다운로드가 완료되었습니다!
) else (
    echo.
    echo [X] 이미지 다운로드에 실패했습니다.
    echo     Docker Hub에 이미지가 아직 업로드되지 않았을 수 있습니다.
    echo     옵션 1(로컬 빌드)을 시도해보세요.
)
pause
goto menu

:: ─── 시작 ───────────────────────────────────────────────
:start
echo.
echo ComfyPack을 시작합니다...
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" up -d
if %errorlevel%==0 (
    echo.
    echo ══════════════════════════════════════════════════════
    echo    ComfyPack이 시작되었습니다!
    echo ══════════════════════════════════════════════════════
    echo.
    echo    ComfyUI:       http://localhost:8188
    echo    Hooking Server: http://localhost:8189
    echo.
    echo    처음 실행 시 모델 로딩에 시간이 걸릴 수 있습니다.
    echo    중지하려면 이 스크립트를 다시 실행하고 옵션 4를 선택하세요.
    echo.
) else (
    echo.
    echo [X] 시작에 실패했습니다. 오류 메시지를 확인하세요.
)
pause
goto menu

:: ─── 중지 ───────────────────────────────────────────────
:stop
echo.
echo ComfyPack을 중지합니다...
docker compose -f "%PROJECT_DIR%\docker-compose.yml" down
echo [OK] ComfyPack이 중지되었습니다.
pause
goto menu

:: ─── 상태 확인 ──────────────────────────────────────────
:status
echo.
echo ComfyPack 상태:
echo.
docker compose -f "%PROJECT_DIR%\docker-compose.yml" ps
echo.
pause
goto menu

:: ─── 설정 초기화 ────────────────────────────────────────
:reset
echo.
del "%ENV_FILE%" 2>nul
echo [OK] .env 파일이 삭제되었습니다. 다음 실행 시 다시 설정합니다.
pause
goto menu
